### ISSUE TITLE
Peer dependency requirement failing when used with latest eslint (eslint@4.16.0)

### ISSUE THREAD

**Issue by devendrawani** [AlexMost/eslint-plugin-deprecate#5]
Command _npm install eslint-plugin-deprecate --save-dev_  failing with installation error when attempted with latest eslint release

npm ERR! Darwin 17.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "eslint-plugin-deprecate" "--save-dev"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package eslint@4.16.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer eslint-plugin-deprecate@0.5.0 wants eslint@^2.0.0 || ^3.0.0

**Comment by devendrawani** [comment]
@AlexMost Is there any specific reason to restrict peer dependency to eslint 2.0.0 or 3.0.0

**Comment by AlexMost** [comment]
thanks for your report! Actually, there is no such reason, will fix that soon.

**Comment by AlexMost** [comment]
so, as it works well with eslint `4.x` i added it to allowed peer dependencies - https://github.com/AlexMost/eslint-plugin-deprecate/commit/e65c32ad434ab541394728a419e447c44c985ab6
`0.5.1` version is available already, so you can check it.

**Comment by devendrawani** [comment]
Perfect. Thanks

**Comment by mauris** [comment]
Hi @AlexMost, I think you've missed out adding eslint 4.x to the allowed peer dependencies. commit e65c32a shows not change to `package.json` in relation to peer dependencies. master still shows `^2.0.0 || ^3.0.0` only. The missing peer dependency warning still shows for eslint 4.19.1 (installed today).

**Comment by AlexMost** [comment]
Oh, here is a fix - https://github.com/AlexMost/eslint-plugin-deprecate/commit/98e3267d88a73d36dcb998e6b9e3e7cb2718e633

You can try it in `0.5.4` version.

**Comment by mauris** [comment]
Thanks for the quick update. got it and doesn't complain with eslint 4.x 👍 👍 👍
