### ISSUE TITLE
Versioning of this package is off

### ISSUE THREAD

**Issue by johannes-scharlach** [AlexMost/eslint-plugin-deprecate#7]
Hi @AlexMost,

I just wanted to use the latest version if eslint-plugin-deprecate with the fix you released yesterday. However, I am currently relying on version `0.5.1`, which is published [on npm (click on "Versions")](https://www.npmjs.com/package/eslint-plugin-deprecate). There is also a tag 0.5.0 in this repository, but no tag 0.5.1 and it seems that version was never merged to master.

Would it be possible to re-release as version `0.5.2`?

**Comment by AlexMost** [comment]
Thanks for the report! Version `0.5.2` is available on npm.
