### ISSUE TITLE
Intended? Bug in import rule

### ISSUE THREAD

**Issue by bel0v** [AlexMost/eslint-plugin-deprecate#9]
Hi and thanks for the plugin.

We've faced a following issue:
Say we have a rule:
```
    "deprecate/import": [
      "error",
      { "name": "app/elements/deprecated", "use": "a new fancy element" }
    ]
```
But due to indexing, we've got many imports like this:
```
import {OkayElement1, OkayElement2 } from 'app/elements'
```
which also triggers an error.

This happens because of the line 69 in `import.js`:
```
filter(([importString]) => importString.includes(importPath))
```
which should be vice versa,
```
importPath.includes(importString))
``` 
I've forked the repo and fixed it for us, but I noticed that you have tests for that behaviour. E.g.:
```
        {
            code: 'import a from "Legacy"',
            parser: 'babel-eslint',
            options: [{ name: 'path/to/Legacy', use: 'New' }],
            errors: [{
                message: 'Module path/to/Legacy is deprecated. Use New instead.'
            }]
        },
```
you consider `Legacy` module to be deprecated, even though in the rule only specific module is stated, namely the one located in `/path/to/`.
From my perspective this is not right and causes issues like ours (partly paths overlapping) or conflicting module names.

If you agree I can provide a PR to fix the behaviour.

**Comment by AlexMost** [comment]
Hey, sorry for the late response. Just have missed your message. This issue can be solved by `nameRegExp` option in 0.7.0. This option allows you to set a regular expression that will validate your import. You can see an examples in a doc - https://github.com/AlexMost/eslint-plugin-deprecate/blob/master/docs/rules/import.md
